/*
 * generated by Xtext 2.14.0
 */
package unice.epu.carpilot.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import unice.epu.carpilot.xtext.ui.internal.XtextActivator;

public class CarpilotUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("unice.epu.carpilot.xtext.Carpilot");
	}

}
