/**
 * generated by Xtext 2.14.0
 */
package unice.epu.carpilot.xtext;

import unice.epu.carpilot.xtext.AbstractCarpilotRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class CarpilotRuntimeModule extends AbstractCarpilotRuntimeModule {
}
