/**
 * generated by Xtext 2.14.0
 */
package unice.epu.carpilot.xtext;

import unice.epu.carpilot.xtext.CarpilotStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class CarpilotStandaloneSetup extends CarpilotStandaloneSetupGenerated {
  public static void doSetup() {
    new CarpilotStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
