/*
 * generated by Xtext 2.14.0
 */
package unice.epu.carpilot.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCarpilotScopeProvider extends DelegatingScopeProvider {
}
