/**
 * generated by Xtext 2.14.0
 */
package unice.epu.carpilot.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import unice.epu.carpilot.xtext.ui.AbstractCarpilotUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class CarpilotUiModule extends AbstractCarpilotUiModule {
  public CarpilotUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
