/**
 * generated by Xtext 2.14.0
 */
package unice.epu.carpilot.xtext.ui.contentassist;

import unice.epu.carpilot.xtext.ui.contentassist.AbstractCarpilotProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class CarpilotProposalProvider extends AbstractCarpilotProposalProvider {
}
