/**
 * generated by Xtext 2.14.0
 */
package unice.epu.carpilot.xtext.scoping;

import unice.epu.carpilot.xtext.scoping.AbstractCarpilotScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class CarpilotScopeProvider extends AbstractCarpilotScopeProvider {
}
