/**
 * generated by Xtext 2.14.0
 */
package unice.epu.carpilot.xtext.ide;

import unice.epu.carpilot.xtext.ide.AbstractCarpilotIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class CarpilotIdeModule extends AbstractCarpilotIdeModule {
}
