/*
 * generated by Xtext 2.14.0
 */
package unice.epu.carpilot.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CarpilotStandaloneSetup extends CarpilotStandaloneSetupGenerated {

	def static void doSetup() {
		new CarpilotStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
