/**
 * generated by Xtext 2.14.0
 */
package unice.epu.carpilot.xtext.validation;

import unice.epu.carpilot.xtext.validation.AbstractCarpilotValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class CarpilotValidator extends AbstractCarpilotValidator {
}
