/*
 * generated by Xtext 2.14.0
 */
package unice.epu.carpilot.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class CarpilotAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("unice/epu/carpilot/xtext/parser/antlr/internal/InternalCarpilot.tokens");
	}
}
