/*
 * generated by Xtext 2.14.0
 */
package unice.epu.carpilot.xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import unice.epu.carpilot.xtext.parser.antlr.internal.InternalCarpilotParser;
import unice.epu.carpilot.xtext.services.CarpilotGrammarAccess;

public class CarpilotParser extends AbstractAntlrParser {

	@Inject
	private CarpilotGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCarpilotParser createParser(XtextTokenStream stream) {
		return new InternalCarpilotParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Car";
	}

	public CarpilotGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CarpilotGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
